# Generated by Django 3.0.7 on 2020-06-08 06:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('journal_title', models.CharField(max_length=50)),
                ('journal_info', jsonfield.fields.JSONField(default=dict)),
                ('borrow_time', models.DateTimeField(auto_now_add=True, verbose_name='借阅日期')),
                ('return_time', models.DateTimeField(auto_now_add=True, verbose_name='归还日期')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=50)),
                ('cnsn', models.CharField(max_length=20)),
                ('issn', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('publisher_area', jsonfield.fields.JSONField(default=dict)),
                ('publisher', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=50)),
                ('journal_info', jsonfield.fields.JSONField(default=dict)),
                ('paper_title', models.CharField(max_length=70)),
                ('paper_info', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=50)),
                ('journal_info', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=20)),
                ('journal_name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True, verbose_name='订阅日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('authority', models.SmallIntegerField()),
            ],
        ),
    ]
