# Generated by Django 3.0.7 on 2020-06-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_manage_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='journal_title',
            new_name='journal_name',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='journal_title',
            new_name='journal_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='journal_title',
            new_name='journal_name',
        ),
    ]
