# Generated by Django 3.0.7 on 2020-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_manage_system', '0002_auto_20200609_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='has_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_time',
            field=models.DateTimeField(verbose_name='归还日期'),
        ),
    ]
